import Head from "next/head";

export default function Home() {
  return (
    <>
      <Head>
        <title>Shing Hao Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <header>
          <nav></nav>
        </header>
        <section className="bg-blue-900 min-h-screen">
          <h1>hello!</h1>
        </section>
      </main>
    </>
  );
}
