import Head from "next/head";
import Navbar from "@/components/navbar/Navbar";
import HeroSection from "@/components/Hero";
import AboutSection from "@/components/about/About";
import WorkSection from "@/components/work/Work";
import PortfolioSection from "@/components/portfolio/Portfolio";
import Footer from "@/components/Footer";
import { useState, useEffect } from "react";
import "animate.css/animate.min.css";
import PacmanLoader from "react-spinners/PacmanLoader";

export default function Home() {
  const LOADTIME = 3000;

  const [darkMode, setDarkMode] = useState(true);
  const [showPage, setShowPage] = useState(true);

  useEffect(() => {
    setInterval(() => {
      setShowPage(true);
    }, LOADTIME);
  });

  const handleDarkModeSwitch = () => {
    setDarkMode(!darkMode);
  };

  const loader = () => {
    return (
      <div className="h-screen w-screen bg-primary-bg-dark flex justify-center items-center">
        <PacmanLoader color="#36d7b7" />
      </div>
    );
  };

  return (
    <div className={darkMode ? "dark" : ""}>
      <Head>
        <title>Shing Hao Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <link
          rel="stylesheet"
          href="https://cdnjs.cloudflare.com/ajax/libs/animate.css/4.1.1/animate.min.css"
        />

        <link
          rel="stylesheet"
          href="https://fonts.googleapis.com/css?family=Josefin+Slab"
        ></link>
      </Head>
      {!showPage && loader()}
      {showPage && (
        <main
          className="bg-primary-bg-light text-primary-text-dark dark:bg-primary-bg-dark dark:text-primary-text-light
         "
        >
          <Navbar
            handleDarkModeSwitch={handleDarkModeSwitch}
            darkMode={darkMode}
          />
          <HeroSection />
          <AboutSection />
          <WorkSection />
          <PortfolioSection />
          <Footer />
        </main>
      )}
    </div>
  );
}
