import Head from "next/head";
import Navbar from "@/components/Navbar";
import SkillCard from "@/components/SkillCard";
export default function Home() {
  const buttonPrimaryStyle = ``;

  return (
    <>
      <Head>
        <title>Shing Hao Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <link
          rel="stylesheet"
          href="https://fonts.googleapis.com/css?family=Josefin+Slab"
        ></link>
      </Head>
      <main className="primary-bg-light text-primary-text-dark">
        <Navbar />
        {/* Landing Page */}
        <section className="min-h-screen flex justify-center">
          <div className="grid grid-flow-row gap-11 items-center justify-items-center content-center">
            <p className="pt-[11rem] text-7xl font-bold">Hi, I'm</p>
            <h2 className="text-7xl font-bold">Shing Hao</h2>
            <h3 className="text-4xl">Web // Software Developer</h3>
            <a href="mailto:sohshinghao@gmail.com">
              <button className="w-btn-l h-btn-primary rounded-btn-primary hover:shadow-skills-card text-primary-text-light bg-gradient-to-r from-primary-btn-blue to-teal-500 font-bold">
                Let's Chat!
              </button>
            </a>
          </div>
        </section>

        {/* About me*/}
        <section className="min-h-screen px-[12.8rem] pt-60">
          <div className="grid grid-cols-10 gap-x-8">
            <h2 className="col-span-6 text-5xl font-bold pb-16">
              Nice to meet you!
            </h2>
            <p className="text-3xl col-span-7 pr-8">
              Hi, I’m Soh Shing Hao, a year 3 Computer Science undergraduate
              with a passion for building impactful products. I love solving
              problems and learning new technologies. <br /> <br /> I am
              currently seeking internship opportunities in web and software
              development.&nbsp;
              <a
                href="mailto:sohshinghao@gmail.com"
                className="bg-primary-blue font-bold underline text-primary-btn-blue"
              >
                Contact Me!
              </a>
            </p>
            <div className="col-start-8 row-start-1 row-span-3 self-center relative bg-gradient-to-b from-primary-btn-blue rounded-full w-[30rem] h-[30rem]">
              <img
                src="shing-memoji-laptop.PNG"
                alt="Avatar of boy using macbook"
                className="rounded-full"
              />
            </div>
            <hr className="row-start-3 col-span-7 h-px my-16 bg-gray-200 border-0 dark:bg-gray-700"></hr>
          </div>
          <div>
            <h3 className="text-4xl mt-4 mb-16 text-center font-bold">
              Technologies:
            </h3>
            <ul className="grid grid-cols-5 gap-16 max-w-max m-auto">
              <li>
                <SkillCard
                  src="icons8-html-5-96.PNG"
                  alt="html icon"
                  text="HTML"
                />
              </li>
              <li>
                <SkillCard src="icons8-css3-96.PNG" alt="css icon" text="CSS" />
              </li>
              <li>
                <SkillCard
                  src="icons8-javascript-96.PNG"
                  alt="javascript icon"
                  text="JavaScript"
                />
              </li>
              <li>
                <SkillCard
                  src="icons8-react-native-96.PNG"
                  alt="react icon"
                  text="React"
                />
              </li>
              <li>
                <SkillCard
                  src="icons8-tailwindcss-96.PNG"
                  alt="tailwindcss icon"
                  text="Tailwindcss"
                />
              </li>

              <li>
                <SkillCard src="icons8-c++-96.PNG" alt="c++ icon" text="C++" />
              </li>
              <li>
                <SkillCard
                  src="icons8-python-96.PNG"
                  alt="python icon"
                  text="Python"
                />
              </li>
              <li>
                <SkillCard src="icons8-git-96.PNG" alt="git icon" text="Git" />
              </li>
              <li>
                <SkillCard
                  src="icons8-unity-96.PNG"
                  alt="unity icon"
                  text="Unity"
                />
              </li>

              <li>
                <SkillCard
                  src="icons8-adobe-photoshop-96.PNG"
                  alt="photoshop icon"
                  text="Photoshop"
                />
              </li>
            </ul>
          </div>
        </section>
        {/* Work Experience */}
        <section className="min-h-screen px-[12.8rem] pt-60 mb-48 h-[calc(100vh-9rem)]">
          <h2 className="text-5xl font-bold pb-16">Work Experience</h2>
          <div className="grid grid-cols-10 gap-8">
            <div className="col-span-7">
              <h3 className="text-4xl font-bold">Serl.io</h3>
              <div className="flex justify-between">
                <p className="text-4xl">Software Developer (Contract)</p>
                <p className="text-xl">May 22 - Nov 22</p>
              </div>
              <ul className="my-8 list-disc mx-12">
                <li>
                  Developed multiple end-to-end
                  <span className="font-bold text-3xl text-primary-btn-blue">
                    {" "}
                    Mixed Reality{" "}
                  </span>{" "}
                  applications for the
                  <span className="font-bold text-3xl text-primary-btn-blue">
                    {" "}
                    Microsoft Hololens 2{" "}
                  </span>
                </li>
                <li>
                  Worked on{" "}
                  <span className="font-bold text-3xl text-primary-btn-blue">
                    web console{" "}
                  </span>
                  applications
                </li>
                <li>
                  Conducted regular
                  <span className="font-bold text-3xl text-primary-btn-blue">
                    {" "}
                    product demos{" "}
                  </span>{" "}
                  for clients{" "}
                </li>
                <li>
                  Hosted booth solo at Semicon 2022 in Penang, where I generated
                  business leads from international clients
                </li>
              </ul>
            </div>
            <div className="w-[30rem] h-[30rem] self-end">
              <img
                src="boy-using-hololens.PNG"
                alt="Avatar of boy using macbook"
                className="rounded-full"
              />
            </div>
          </div>
          <ul className="grid grid-flow-col max-w-max gap-12">
            <li className="flex flex-col items-center justify-center">
              <img
                src="icons8-unity-96.PNG"
                alt="unity icon"
                className="w-24 "
              />
              <p className="text-xl">Unity</p>
            </li>
            <li className="flex flex-col items-center justify-center">
              <img
                src="icons8-c-sharp-logo-96.PNG"
                alt="c sharp icon"
                className="w-24 "
              />
              <p className="text-xl">C#</p>
            </li>
            <li className="flex flex-col items-center justify-center">
              <img
                src="icons8-javascript-96.PNG"
                alt="javascript icon"
                className="w-24 "
              />
              <p className="text-xl">JavaScript</p>
            </li>
            <li className="flex flex-col items-center justify-center">
              <img
                src="icons8-html-5-96.PNG"
                alt="html icon"
                className="w-24 "
              />
              <p className="text-xl">HTML</p>
            </li>
            <li className="flex flex-col items-center justify-center">
              <img src="icons8-css3-96.PNG" alt="css icon" className="w-24 " />
              <p className="text-xl">CSS</p>
            </li>
          </ul>
        </section>
        {/*Portfolio*/}
        <section className="min-h-screen px-[12.8rem] pt-60  h-[calc(100vh-9rem)] flex">
          <h2 className="text-5xl font-bold pb-16">Project Highlights</h2>
        </section>
      </main>
    </>
  );
}
